// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzdnevbtvmcoqmrlxpvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6ZG5ldmJ0dm1jb3Ftcmx4cHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNjYwODMsImV4cCI6MjA1Mjk0MjA4M30.9WQplI028jEZSuOuddYj2Vp9i7tppKhqVG9lXjsrmZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);